### ISSUE TITLE
Predictions docs and code mismatch

### ISSUE THREAD

**Issue by kurtjcu** [PyTorchLightning/lightning-flash#181] opened 2021-03-16 02:42 UTC
Documentation describes using the string if an image for inference, code treats a string as a directory

**Comment by ethanwharris** [comment] 2021-04-21 16:45
Hi @kurtjcu, thanks for the issue! We've been undergoing a big refactor and the example from the docs is now working :smiley: So I'm closing this, feel free to re-open if you find that the issue isn't fixed for you.

**Closed by ethanwharris** 2021-04-21 16:45 UTC
Labels: documentation
