### ISSUE TITLE
TypeError: list indices must be integers or slices, not DefaultDataKeys when training Object Detection Model

### ISSUE THREAD

**Issue by hzitoun** [PyTorchLightning/lightning-flash#414] opened 2021-06-16 00:58 UTC
## 🐛 Bug
I've spent days making the data augmentation work for Object Detection but errors keep poping up. I don't know if I'm reinventing the wheels or you are missing a lot in term data preparation/augmentation documentation for object detection. I'm about to give up...

Following #409 (always not resolved) I've created a custom data augmentation transformation using albumentations. However it fails with a weird message when starting training (when we fix the error I can make a PR for integrating albumentations with pytorch lightning flash): 

```python
File "train.py", line 93, in train
    trainer.finetune(model, datamodule=datamodule)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flash/core/trainer.py", line 148, in finetune
    return super().fit(model, train_dataloader, val_dataloaders, datamodule)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 458, in fit
    self._run(model)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 756, in _run
    self.dispatch()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 807, in run_stage
    return self.run_train()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 842, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1107, in run_sanity_check
    self.run_evaluation()
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 962, in run_evaluation
    output = self.evaluation_loop.evaluation_step(batch, batch_idx, dataloader_idx)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 174, in evaluation_step
    output = self.trainer.accelerator.validation_step(args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 226, in validation_step
    return self.training_type_plugin.validation_step(*args)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/ddp.py", line 322, in validation_step
    return self.model(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/lib/python3/dist-packages/torch/nn/parallel/distributed.py", line 705, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 57, in forward
    output = self.module.validation_step(*inputs, **kwargs)
  File "/home/ubuntu/.local/lib/python3.8/site-packages/flash/image/detection/model.py", line 179, in validation_step
    images, targets = batch[DefaultDataKeys.INPUT], batch[DefaultDataKeys.TARGET]
TypeError: list indices must be integers or slices, not DefaultDataKeys
```

Before that it was failing with `RuntimeError: each element in list of batch should be of equal size` but this torch vision tip of custom collate : `lambda x:x` "fixes" it https://github.com/pytorch/vision/issues/2624 

What is going on? 

### To Reproduce

```python

import albumentations as A
from albumentations.pytorch.transforms import ToTensorV2
from PIL import Image
import cv2

import flash
from flash.core.data.utils import download_data
from flash.image import ObjectDetectionData, ObjectDetector
from pytorch_lightning import seed_everything
import numpy

import logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger(__name__)

seed_everything(42)

   image_size = 1024

    train_transform = A.Compose(
        [
            A.Resize(height=image_size, width=image_size, p=1),
            A.OneOf([
                A.HueSaturationValue(hue_shift_limit=20, sat_shift_limit=20,
                                     val_shift_limit=20, p=0.5),
                A.RandomBrightnessContrast(brightness_limit=0.2,
                                           contrast_limit=0.2, p=0.5),
            ], p=0.9),
            A.ToGray(p=0.01),
            A.VerticalFlip(p=0.5),
            A.HorizontalFlip(p=0.5),
            A.ShiftScaleRotate(p=0.5),
            A.Cutout(num_holes=10, max_h_size=32, max_w_size=32, fill_value=0, p=0.5),
            ToTensorV2(p=1)
        ],
        p=1.0,
        bbox_params=A.BboxParams(
            format='pascal_voc',
            min_area=0,
            min_visibility=0,
            label_fields=['labels']
        )
    )

    valid_transform = A.Compose(
        [
            A.Resize(height=image_size, width=image_size, p=1),
            ToTensorV2(p=1)
        ],
        p=1.0,
        bbox_params=A.BboxParams(
            format='pascal_voc',
            min_area=0,
            min_visibility=0,
            label_fields=['labels']
        )
    )

    test_transform = A.Compose(
        [
            A.Resize(height=image_size, width=image_size, p=1),
            ToTensorV2(p=1)
        ],
        p=1.0,
        bbox_params=A.BboxParams(
            format='pascal_voc',
            min_area=0,
            min_visibility=0,
            label_fields=['labels']
        )
    )

    datamodule = ObjectDetectionData.from_coco(
        train_folder="data_coco/train",
        train_ann_file="data_coco/train/_annotations.coco.json",
        train_transform={
            'pre_tensor_transform': lambda sample: transform_using_albu(sample, train_transform),
            'collate' : lambda x: x
        },
        val_transform={
         'pre_tensor_transform': lambda sample: transform_using_albu(sample, valid_transform),
          'collate': lambda x: x
        },
        test_transform={
         'pre_tensor_transform': lambda sample: transform_using_albu(sample, test_transform),
         'collate': lambda x: x
       },
        val_split=0.2,
        batch_size=8,
        num_workers=4,
    )

    model = ObjectDetector(model="retinanet", backbone="resnet101", num_classes=datamodule.num_classes, fpn=True)

    # 4. Create the trainer
    trainer = flash.Trainer(max_epochs=1, gpus=2, accelerator='ddp', limit_train_batches=1, limit_val_batches=1, checkpoint_callback=True)

    # 5. Finetune the model
    trainer.finetune(model, datamodule=datamodule)


def transform_using_albu(sample, train_transform):
        labels = sample['target']['labels']
        image = to_cv(sample['input'])
        transformed = train_transform(image=image, bboxes=sample['target']['boxes'], labels=sample['target']['labels'])
        trans_bboxes = [list(boxes) for boxes in transformed["bboxes"]]
        area = [calculate_area(boxes) for boxes in trans_bboxes]
        return {
            'input': transformed["image"],
            'target': {
              'boxes': trans_bboxes,
              'labels': labels,
              'image_id': sample['target']['image_id'],
              'area': area,
              'iscrowd': [0 for _ in trans_bboxes]}
            }

```
### Environment

 - PyTorch Version: 1.8
 - OS (e.g., Linux): MacOS
 - How you installed PyTorch: pip 
 - Python version: 3.7
 - CUDA/cuDNN version: 11
 - GPU models and configuration: 2 A 6000

### Additional context

It is necessary to provide a clear and working example of augmenting and resizing images for object detection using torchvision transformers or albumentations.

**Comment by ethanwharris** [comment] 2021-06-16 08:38
Hi @hzitoun Thanks for the issue! Sorry that your experience with Flash hasn't been very smooth. Using a custom collate is the right idea, but rather than an identity function you need the following:
```
def collate(samples: Sequence[Dict[str, Any]]) -> Dict[str, Sequence[Any]]:
    return {key: [sample[key] for sample in samples] for key in samples[0]}
```
Your collate gives an output like this:
```
[{sample 1}, {sample 2}, {sample 3}, ...]
```
The new collate does this:
```
{key1: [sample1[key1], sample2[key1], ...], key2: [sample1[key2], sample2[key2], ...], ...}
```

Hope that helps :smiley:

**Comment by hzitoun** [comment] 2021-06-16 09:01
@ethanwharris thanks for your answer it fixes the error but throws another one which is `TypeError: Expected input images to be of floating type (in range [0, 1]), but found type torch.uint8 instead`? I'm missing an image normalization (doesn't the model take care of)?

**Comment by ethanwharris** [comment] 2021-06-16 09:10
Hi @hzitoun, could you share the full trace? I'm not very familiar with albumentations. What might work is if you remove the `ToTensorV2` and use something else instead. We use this:
```
"to_tensor_transform": nn.Sequential(
    ApplyToKeys('input', torchvision.transforms.ToTensor()),
    ApplyToKeys(
        'target',
        nn.Sequential(
            ApplyToKeys('boxes', torch.as_tensor),
            ApplyToKeys('labels', torch.as_tensor),
            ApplyToKeys('image_id', torch.as_tensor),
            ApplyToKeys('area', torch.as_tensor),
            ApplyToKeys('iscrowd', torch.as_tensor),
        )
    ),
),
```

So you could do:
```
train_transform={
    'pre_tensor_transform': lambda sample: transform_using_albu(sample, train_transform),
    'to_tensor_transform': nn.Sequential(
        ApplyToKeys('input', torchvision.transforms.ToTensor()),
        ApplyToKeys(
            'target',
            nn.Sequential(
                ApplyToKeys('boxes', torch.as_tensor),
                ApplyToKeys('labels', torch.as_tensor),
                ApplyToKeys('image_id', torch.as_tensor),
                ApplyToKeys('area', torch.as_tensor),
                ApplyToKeys('iscrowd', torch.as_tensor),
            )
        ),
    ),
    'collate' : lambda x: x
}
```

Hope that helps :smiley:

**Comment by hzitoun** [comment] 2021-06-23 09:49
@ethanwharris  should I keep the same `image_id` or create a unique one for each augmented data?

**Comment by ethanwharris** [comment] 2021-06-23 09:56
Hi @hzitoun The `image_id` should be kept as it is just the ID of the image / annotations from COCO :smiley:

**Comment by hzitoun** [comment] 2021-06-23 10:10
Thanks! But went through another error! 

```
/usr/local/lib/python3.7/dist-packages/pytorch_lightning/metrics/__init__.py:44: LightningDeprecationWarning: `pytorch_lightning.metrics.*` module has been renamed to `torchmetrics.*` and split off to its own package (https://github.com/PyTorchLightning/metrics) since v1.3 and will be removed in v1.5
  "`pytorch_lightning.metrics.*` module has been renamed to `torchmetrics.*` and split off to its own package"
/usr/local/lib/python3.7/dist-packages/distributed/config.py:20: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  defaults = yaml.load(f)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-78df23761c79> in <module>()
      7 from flash.core.data.utils import download_data
      8 from flash.core.data.transforms import ApplyToKeys
----> 9 from flash.image import ObjectDetectionData, ObjectDetector
     10 from pytorch_lightning import seed_everything
     11 import numpy

2 frames
/usr/local/lib/python3.7/dist-packages/flash/image/embedding/model.py in <module>()
     15 
     16 import torch
---> 17 from pytorch_lightning.utilities.distributed import rank_zero_warn
     18 from torch import nn
     19 from torch.nn import functional as F

ImportError: cannot import name 'rank_zero_warn' from 'pytorch_lightning.utilities.distributed' (/usr/local/lib/python3.7/dist-packages/pytorch_lightning/utilities/distributed.py)
```

It is on Colab using torch 1.8 and torchvision 0.9.0

**Comment by ethanwharris** [comment] 2021-06-23 10:13
Ah yes, this one is caused by the most recent pytorch lightning version. They are working on a patch, but if you could do `pip install 'pytorch-lightning==1.3.6'` that should fix the error :smiley:

**Comment by hzitoun** [comment] 2021-06-23 15:12
Thanks that fixed it! However the augmentation doesn't work! Giving up! Will generated augemented data on my disk then loading them with datamodule as new files... 

But how can I just resize my images before giving them to the model ? I'm running into CUDA OOF no way to start training!

**Comment by ethanwharris** [comment] 2021-06-23 15:43
Hi @hzitoun, this is working for me:
```
import torch
from torch import nn
from flash.core.data.transforms import ApplyToKeys


def collate(samples):
    return {key: [sample[key] for sample in samples] for key in samples[0]}


transform = {
    "pre_tensor_transform": ApplyToKeys('input', torchvision.transforms.Resize((64, 64))),
    "to_tensor_transform": nn.Sequential(
        ApplyToKeys('input', torchvision.transforms.ToTensor()),
        ApplyToKeys(
            'target',
            nn.Sequential(
                ApplyToKeys('boxes', torch.as_tensor),
                ApplyToKeys('labels', torch.as_tensor),
                ApplyToKeys('image_id', torch.as_tensor),
                ApplyToKeys('area', torch.as_tensor),
                ApplyToKeys('iscrowd', torch.as_tensor),
            )
        ),
    ),
    "collate": collate,
}

# 2. Load the Data
datamodule = ObjectDetectionData.from_coco(
    train_folder="data/coco128/images/train2017/",
    train_ann_file="data/coco128/annotations/instances_train2017.json",
    val_split=0.3,
    batch_size=4,
    num_workers=4,
    train_transform=transform,
)
```

Hope that helps :smiley:

**Comment by hzitoun** [comment] 2021-06-23 22:38
thanks @ethanwharris! Does `"pre_tensor_transform": ApplyToKeys('input', torchvision.transforms.Resize((64, 64))) ` adjust the boxes as well?

**Comment by hzitoun** [comment] 2021-06-25 07:43
@ethanwharris any idea?

**Comment by ethanwharris** [comment] 2021-06-26 08:46
Hi @hzitoun My apologies, the example I gave won't resize the bounding boxes. Let me take a look on Monday and get an example that does resize bounding boxes correctly with albumentations. Thanks for sticking with it! :smiley:

**Comment by hzitoun** [comment] 2021-06-28 10:30
@ethanwharris waiting :)

**Comment by ethanwharris** [comment] 2021-06-28 11:48
@hzitoun This is working for me:
```
from functools import partial
import torch
from torch import nn
import torchvision
from flash.core.data.transforms import ApplyToKeys
import albumentations as A


def collate(samples):
    return {key: [sample[key] for sample in samples] for key in samples[0]}


def format_bbox(bbox):
    """Fix cases where bboxes are tiny and trigger underflow / overflow."""
    if bbox[2] <= bbox[0]:
        bbox[2] = bbox[0] + 1
    if bbox[3] <= bbox[1]:
        bbox[3] = bbox[1] + 1
    return bbox


def albumentations_transform(transform, inputs):
    input, target = inputs
    image = np.array(input)
    bboxes = target["boxes"]
    labels = target["labels"]
    # Fix FP errors with underflow / overflow in bboxes
    bboxes = [[round(coord) for coord in bbox] for bbox in bboxes]
    bboxes = [format_bbox(bbox) for bbox in bboxes]
    result = transform(image=image, bboxes=bboxes, class_labels=labels)
    target["boxes"] = result["bboxes"]
    target["labels"] = result["class_labels"]
    return PIL.Image.fromarray(result["image"]), target


transform = {
    "pre_tensor_transform": ApplyToKeys(["input", "target"], partial(
        albumentations_transform,
        A.Compose([
            A.Resize(64, 64),
        ], bbox_params=A.BboxParams(format="pascal_voc", label_fields=["class_labels"])),
    )),
    "to_tensor_transform": nn.Sequential(
        ApplyToKeys("input", torchvision.transforms.ToTensor()),
        ApplyToKeys(
            "target",
            nn.Sequential(
                ApplyToKeys("boxes", torch.as_tensor),
                ApplyToKeys("labels", torch.as_tensor),
                ApplyToKeys("image_id", torch.as_tensor),
                ApplyToKeys("area", torch.as_tensor),
                ApplyToKeys("iscrowd", torch.as_tensor),
            )
        ),
    ),
    "collate": collate,
}

# 2. Load the Data
datamodule = ObjectDetectionData.from_coco(
    train_folder="data/coco128/images/train2017/",
    train_ann_file="data/coco128/annotations/instances_train2017.json",
    val_split=0.3,
    batch_size=4,
    num_workers=0,
    train_transform=transform,
    val_transform=transform,
)
```

There are several things here that we can improve in flash to make this better. I'll open some issues later on.

**Comment by hzitoun** [comment] 2021-06-28 13:04
@ethanwharris Be careful, your code doesn't recalculate the area of the bboxes after the transformations. Also you are converting from cv to PIL and from PIL to cv without changing the color channel (BGR and RGB)

**Comment by ethanwharris** [comment] 2021-06-28 13:20
@hzitoun Presumably this code gives you enough of a starting point to customize to your use case? Regarding your points:
- We don't actually use the `area` key for anything as far as I can tell, so it didn't seem important to recalculate it. If you want the area to be correct it should be fairly simple to add that to the above code.
- The conversion to and from PIL is purely to get it working with albumentations and resize doesn't depend on RGB order. The conversion to a valid tensor is handled by torchvision.ToTensor, which takes account of channel orderring.

> Let us be clear, flash doesn't (yet) handle image resizing of input data for objects detection which is a basic thing.

I'm not sure what you mean here. We're not trying to pretend we support or automate something that we don't. We support transforming of the data, it's up to the user to ensure that their transforms work correctly. There are possibly ways that we can automate this to work with albumentations, and we have plans to do this, but we've never claimed to do this already. If you feel that adding support for these transforms is basic, we would welcome a PR :smiley:

**Comment by hzitoun** [comment] 2021-06-28 13:39
@ethanwharris 

> * We don't actually use the `area` key for anything as far as I can tell, so it didn't seem important to recalculate it. If you want the area to be correct it should be fairly simple to add that to the above code.

For the `area`, there is no way to know if it used or not. But, even though, I've already recalculated it `area = [calculate_area(boxes) for boxes in trans_bboxes]` in my first code snippet so when I saw yours I alerted you about that. But if it is not used, I can't predict that.

> * The conversion to and from PIL is purely to get it working with albumentations and resize doesn't depend on RGB order. The conversion to a valid tensor is handled by torchvision.ToTensor, which takes account of channel orderring.

My apologies, I thought you used opencv to convert from PIL to numpy array and the inverse. It is not the case in your example so yes no need to take care of the RGB order it remains the same.

> I'm not sure what you mean here. We're not trying to pretend we support or automate something that we don't. We support transforming of the data, it's up to the user to ensure that their transforms work correctly. There are possibly ways that we can automate this to work with albumentations, and we have plans to do this, but we've never claimed to do this already. If you feel that adding support for these transforms is basic, we would welcome a PR 😃

I meant that the object detection API with flash is not documented well there is only basic examples, and almost any other libraries for object detection gives the possibility of choosing the input size (which I consider a basic config), but in flash it is not the case just to resize the images in case of high resolution ones (that don't fit in CUDA memory evenwith  batch size = 1) you need to write your own transformations, readjust a lot of things and look how much it took us to make it work. 
Yes I'm really thinking about creating a PR for integrating albumentations with flash 😃

**Comment by ethanwharris** [comment] 2021-06-28 13:52
Hi @hzitoun

> For the `area`, there is no way to know if it used or not. But, even though, I've already recalculated it `area = [calculate_area(boxes) for boxes in trans_bboxes]` in my first code snippet so when I saw yours I alerted you about that. But if it is not used, I can't predict that.

Yeah, as far as I can tell we don't use it. I think it would be fine to even remove it from the data source altogether (it worked fine when I did that).

> Yes I'm really thinking about creating a PR for integrating albumentations with flash 😃 but before integrating an external library for doing a lot of things, I was looking for a simpler way just to resize images (and their corresponding bboxes) (remember my previous issue).

Personally, I would prefer to have an external library do these things as we shouldn't try to re-invent the wheel when libraries like albumentations already have the functionality we need. I think what we could do is check if the transforms being passed are albumentations transforms and then wrap them (smiliar to the above wrappers) for the user.

I've opened issues for these in #486 and #487, and an issue to update the docs in #488. Closing this one as we should track these issues seperately. Please feel free to try a PR for any or all of them and we can help out if you get stuck. Thanks :smiley:

**Closed by ethanwharris** 2021-06-28 13:52 UTC
Labels: bug / fix, help wanted
