### ISSUE TITLE
Can't import Flash, fails with OSError: protocol not found

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/lightning-flash#641] opened 2021-08-06 09:08 UTC
### To Reproduce

Running in Kaggle kernel, install from master:
```bash
! git clone https://github.com/PyTorchLightning/lightning-flash.git
! ls -l
! cd lightning-flash && pip install -q .[image]
```
getting:
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-26-e49b907486a9> in <module>
----> 1 import flash
      2 from flash.image import ObjectDetectionData, ObjectDetector
      3 
      4 # 1. Create the DataModule
      5 datamodule = ObjectDetectionData.from_coco(

/opt/conda/lib/python3.7/site-packages/flash/__init__.py in <module>
     20 if _TORCH_AVAILABLE:
     21 
---> 22     from flash.core.data.callback import FlashCallback
     23     from flash.core.data.data_module import DataModule  # noqa: E402
     24     from flash.core.data.data_source import DataSource

/opt/conda/lib/python3.7/site-packages/flash/core/data/callback.py in <module>
      2 from typing import Any, List, Sequence
      3 
----> 4 from pytorch_lightning.callbacks import Callback
      5 from pytorch_lightning.trainer.states import RunningStage
      6 from torch import Tensor

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/__init__.py in <module>
     19 
     20 from pytorch_lightning import metrics  # noqa: E402
---> 21 from pytorch_lightning.callbacks import Callback  # noqa: E402
     22 from pytorch_lightning.core import LightningDataModule, LightningModule  # noqa: E402
     23 from pytorch_lightning.trainer import Trainer  # noqa: E402

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/__init__.py in <module>
     22 from pytorch_lightning.callbacks.prediction_writer import BasePredictionWriter
     23 from pytorch_lightning.callbacks.progress import ProgressBar, ProgressBarBase
---> 24 from pytorch_lightning.callbacks.pruning import ModelPruning
     25 from pytorch_lightning.callbacks.quantization import QuantizationAwareTraining
     26 from pytorch_lightning.callbacks.stochastic_weight_avg import StochasticWeightAveraging

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/callbacks/pruning.py in <module>
     29 import pytorch_lightning as pl
     30 from pytorch_lightning.callbacks.base import Callback
---> 31 from pytorch_lightning.core.lightning import LightningModule
     32 from pytorch_lightning.utilities.apply_func import apply_to_collection
     33 from pytorch_lightning.utilities.distributed import rank_zero_debug, rank_zero_only

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/core/__init__.py in <module>
     14 
     15 from pytorch_lightning.core.datamodule import LightningDataModule
---> 16 from pytorch_lightning.core.lightning import LightningModule
     17 
     18 __all__ = ["LightningDataModule", "LightningModule"]

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/core/lightning.py in <module>
     39 from pytorch_lightning.core.optimizer import LightningOptimizer
     40 from pytorch_lightning.core.saving import ModelIO
---> 41 from pytorch_lightning.trainer.connectors.logger_connector.fx_validator import FxValidator
     42 from pytorch_lightning.utilities import rank_zero_deprecation, rank_zero_warn
     43 from pytorch_lightning.utilities.apply_func import apply_to_collection, convert_to_tensors

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/__init__.py in <module>
     16 """
     17 
---> 18 from pytorch_lightning.trainer.trainer import Trainer
     19 from pytorch_lightning.utilities.seed import seed_everything
     20 

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py in <module>
     29 from pytorch_lightning.core.datamodule import LightningDataModule
     30 from pytorch_lightning.core.memory import ModelSummary
---> 31 from pytorch_lightning.loggers import LightningLoggerBase
     32 from pytorch_lightning.loops import TrainingBatchLoop, TrainingEpochLoop
     33 from pytorch_lightning.loops.dataloader.evaluation_loop import EvaluationLoop

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loggers/__init__.py in <module>
     24 from pytorch_lightning.loggers.neptune import _NEPTUNE_AVAILABLE, NeptuneLogger  # noqa: F401
     25 from pytorch_lightning.loggers.test_tube import _TESTTUBE_AVAILABLE, TestTubeLogger  # noqa: F401
---> 26 from pytorch_lightning.loggers.wandb import _WANDB_AVAILABLE, WandbLogger  # noqa: F401
     27 
     28 if _COMET_AVAILABLE:

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/loggers/wandb.py in <module>
     35 
     36 _WANDB_AVAILABLE = _module_available("wandb")
---> 37 _WANDB_GREATER_EQUAL_0_10_22 = _compare_version("wandb", operator.ge, "0.10.22")
     38 
     39 try:

/opt/conda/lib/python3.7/site-packages/pytorch_lightning/utilities/imports.py in _compare_version(package, op, version)
     52     """
     53     try:
---> 54         pkg = importlib.import_module(package)
     55     except (ModuleNotFoundError, DistributionNotFound):
     56         return False

/opt/conda/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

/opt/conda/lib/python3.7/site-packages/wandb/__init__.py in <module>
     36 if PY3:
     37     TYPE_CHECKING = True
---> 38     from wandb import sdk as wandb_sdk
     39 else:
     40     from wandb import sdk_py27 as wandb_sdk

/opt/conda/lib/python3.7/site-packages/wandb/sdk/__init__.py in <module>
      5 """
      6 
----> 7 from . import wandb_helper as helper  # noqa: F401
      8 from .wandb_alerts import AlertLevel  # noqa: F401
      9 from .wandb_artifacts import Artifact  # noqa: F401

/opt/conda/lib/python3.7/site-packages/wandb/sdk/wandb_helper.py in <module>
      6 from wandb.errors import UsageError
      7 
----> 8 from .lib import config_util
      9 
     10 

/opt/conda/lib/python3.7/site-packages/wandb/sdk/lib/config_util.py in <module>
      6 import six
      7 from wandb.errors import Error
----> 8 from wandb.util import load_yaml
      9 import yaml
     10 

/opt/conda/lib/python3.7/site-packages/wandb/util.py in <module>
     43 from six.moves.collections_abc import Mapping, Sequence
     44 from importlib import import_module
---> 45 import sentry_sdk
     46 from sentry_sdk import capture_exception
     47 from sentry_sdk import capture_message

/opt/conda/lib/python3.7/site-packages/sentry_sdk/__init__.py in <module>
----> 1 from sentry_sdk.hub import Hub, init
      2 from sentry_sdk.scope import Scope
      3 from sentry_sdk.transport import Transport, HttpTransport
      4 from sentry_sdk.client import Client
      5 

/opt/conda/lib/python3.7/site-packages/sentry_sdk/hub.py in <module>
      6 
      7 from sentry_sdk._compat import with_metaclass
----> 8 from sentry_sdk.scope import Scope
      9 from sentry_sdk.client import Client
     10 from sentry_sdk.tracing import Span, Transaction

/opt/conda/lib/python3.7/site-packages/sentry_sdk/scope.py in <module>
      5 from sentry_sdk._functools import wraps
      6 from sentry_sdk._types import MYPY
----> 7 from sentry_sdk.utils import logger, capture_internal_exceptions
      8 from sentry_sdk.tracing import Transaction
      9 from sentry_sdk.attachments import Attachment

/opt/conda/lib/python3.7/site-packages/sentry_sdk/utils.py in <module>
    868 
    869 
--> 870 HAS_REAL_CONTEXTVARS, ContextVar = _get_contextvars()
    871 
    872 CONTEXTVARS_ERROR_MESSAGE = """

/opt/conda/lib/python3.7/site-packages/sentry_sdk/utils.py in _get_contextvars()
    838     See https://docs.sentry.io/platforms/python/contextvars/ for more information.
    839     """
--> 840     if not _is_contextvars_broken():
    841         # aiocontextvars is a PyPI package that ensures that the contextvars
    842         # backport (also a PyPI package) works with asyncio under Python 3.6

/opt/conda/lib/python3.7/site-packages/sentry_sdk/utils.py in _is_contextvars_broken()
    799 
    800     try:
--> 801         from eventlet.patcher import is_monkey_patched  # type: ignore
    802 
    803         if is_monkey_patched("thread"):

/opt/conda/lib/python3.7/site-packages/eventlet/__init__.py in <module>
     15 # access the version.  Also this makes easy_install a little quieter
     16 if os.environ.get('EVENTLET_IMPORT_VERSION_ONLY') != '1':
---> 17     from eventlet import convenience
     18     from eventlet import event
     19     from eventlet import greenpool

/opt/conda/lib/python3.7/site-packages/eventlet/convenience.py in <module>
      5 from eventlet import greenthread
      6 from eventlet import support
----> 7 from eventlet.green import socket
      8 from eventlet.support import greenlets as greenlet
      9 

/opt/conda/lib/python3.7/site-packages/eventlet/green/socket.py in <module>
     19 
     20 if os.environ.get("EVENTLET_NO_GREENDNS", '').lower() != 'yes':
---> 21     from eventlet.support import greendns
     22     gethostbyname = greendns.gethostbyname
     23     getaddrinfo = greendns.getaddrinfo

/opt/conda/lib/python3.7/site-packages/eventlet/support/greendns.py in <module>
     69     setattr(dns.rdtypes, pkg, import_patched('dns.rdtypes.' + pkg))
     70 for pkg in dns.rdtypes.IN.__all__:
---> 71     setattr(dns.rdtypes.IN, pkg, import_patched('dns.rdtypes.IN.' + pkg))
     72 for pkg in dns.rdtypes.ANY.__all__:
     73     setattr(dns.rdtypes.ANY, pkg, import_patched('dns.rdtypes.ANY.' + pkg))

/opt/conda/lib/python3.7/site-packages/eventlet/support/greendns.py in import_patched(module_name)
     59         'ssl': ssl,
     60     }
---> 61     return patcher.import_patched(module_name, **modules)
     62 
     63 

/opt/conda/lib/python3.7/site-packages/eventlet/patcher.py in import_patched(module_name, *additional_modules, **kw_additional_modules)
    133         module_name,
    134         None,
--> 135         *additional_modules + tuple(kw_additional_modules.items()))
    136 
    137 

/opt/conda/lib/python3.7/site-packages/eventlet/patcher.py in inject(module_name, new_globals, *additional_modules)
    107             sys.modules.pop(imported_module_name, None)
    108     try:
--> 109         module = __import__(module_name, {}, {}, module_name.split('.')[:-1])
    110 
    111         if new_globals is not None:

/opt/conda/lib/python3.7/site-packages/dns/rdtypes/IN/WKS.py in <module>
     23 from dns._compat import xrange
     24 
---> 25 _proto_tcp = socket.getprotobyname('tcp')
     26 _proto_udp = socket.getprotobyname('udp')
     27 

OSError: protocol not found
```

### Environment

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by akihironitta** [comment] 2021-08-22 23:16
Closing this since I cannot reproduce this. It could probably be caused by the Kaggle kernel side.

**Closed by akihironitta** 2021-08-22 23:16 UTC
Labels: bug / fix, help wanted
