### ISSUE TITLE
[text] Extendable Backbones and Dataloaders

### ISSUE THREAD

**Issue by aribornstein** [PyTorchLightning/lightning-flash#95] opened 2021-02-09 20:30 UTC
## 🚀 Feature
Backbones and Dataloaders are tightly coupled to tasks this makes it hard for example to use a non huggingface model for text classification or flair embeddings for featurization. 

### Motivation

In order to prevent duplicate tasks for different backbone libraries Flash needs an extendable way of adding backbones to a task.

**Comment by carmocca** [comment] 2021-03-22 15:32
@aribornstein is this a duplicate of https://github.com/PyTorchLightning/lightning-flash/issues/167 ?

**Comment by edgarriba** [comment] 2021-05-03 10:37
@aribornstein backbones api is already merged. Can we close this ?

**Closed** 2021-05-10 10:49 UTC
Labels: API / design, backbone, help wanted, refactors and code health
