### ISSUE TITLE
Fiftyone Image embedder example broken

### ISSUE THREAD

**Issue by ethanwharris** [PyTorchLightning/lightning-flash#1031] opened 2021-12-06 19:09 UTC
## 🐛 Bug

Following the addition of the VISSL training strategies to the image embedder, the FiftyOne image embedding example is no longer correct.

**Comment by ar90n** [comment] 2022-03-25 05:23
Hi there.
I'm so interested in this issue. If anyone is not assigned this issue yet, please assign me.
For now, I have regenerated this issue in my local environment and fixed it with ugly codes.

In my environment, the vanilla image embedding example whose path is `flash_example/image_embedder.py` doesn’t work too. I think this is caused by the same reason as the fiftyone integration example.

**Comment by ethanwharris** [comment] 2022-03-30 12:53
@ar90n Awesome! We have some fixes for the image embedder that are about to go out, but ideally we would remove the current dependency on vissl altogether (this should only be required if you want to use the SSL training support). I think the two changes we need to make are:
1. add support to the vissl integration to use any backbone from the `ImageClassifier` backbones (rather than just the vissl backbones it supports at the moment).
2. make the `training_strategy` argument and dependency on vissl optional and only required if you want to train / val / test with the `ImageEmbedder`

I have a PoC for the first one, so I can finish that up then you could take the second? Let me know if that sounds good to you, I'll assign us both to the issue :smiley:

**Comment by ar90n** [comment] 2022-03-31 16:52
@ethanwharris 
Thanks for your reply and for assigning this issue to me.  I agree with your suggestions completely. I'll try to make a PR about the second change you said above. In fact,  I also felt that ImageEmbedder is too coupled with vissl.

**Comment by ar90n** [comment] 2022-04-04 06:39
@ethanwharris 
I created a PR about the second change you said above based on #1264. I will change its status to Ready for review after #1264 is merged. If I misunderstand what shoud I do, please comment. I'll fix it.

https://github.com/PyTorchLightning/lightning-flash/pull/1271

**Comment by ethanwharris** [comment] 2022-04-04 08:36
@ar90n Awesome!!! Will take a look and get back to you 😃

**Closed** 2022-05-03 13:04 UTC
Labels: bug / fix, documentation, help wanted
